archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: binary
  replacements:
    amd64: x86_64
    darwin: Darwin
    linux: Linux
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
